#!/bin/sh


data_build_file='/buildapp/data_build.py'
project_manage_file='/manage.py'
db_file='/db.sqlite3'

cd ..

root_directory=$(pwd)
> $root_directory$db_file
$(which python) $root_directory$project_manage_file makemigrations
$(which python) $root_directory$project_manage_file migrate
$(which python) $root_directory$data_build_file
