#!/bin/sh

pythonpath=$(which python3)
root_directory=$(pwd)
echo $root_directory

requirement_file='/requirements.txt'
data_build_dir='/buildapp'
echo $(pwd)
# pip install --user pipenv

$(which virtualenvwrapper.sh) tala_proj
pip install -r $root_directory$requirement_file

./data_build